import fs from 'fs';
import path from 'path';

// This script generates the complete, rich library of 520+ chemical compounds
// with realistic reactions, recipes, equations, hazard levels, enthalpies, colors,
// and educational facts.

interface CompoundDef {
  id: string;
  name: string;
  formula: string;
  category: 'oxide' | 'acid' | 'base' | 'alkali' | 'salt' | 'hydrocarbon' | 'alcohol' | 'organic' | 'polymer' | 'rare_matter';
  state: 'gas' | 'liquid' | 'solid' | 'plasma';
  appearance: string;
  description: string;
  hazard: 'safe' | 'irritant' | 'flammable' | 'corrosive' | 'toxic' | 'explosive' | 'radioactive';
  bondType: 'covalent' | 'ionic' | 'metallic' | 'polar covalent' | 'polar-covalent' | 'aromatic' | 'coordinate';
  color: string;
  glowColor?: string;
  recipe: string[];
  condition?: { heat?: boolean; electricity?: boolean; catalyst?: boolean };
  equation: string;
  enthalpy?: string;
  funFact?: string;
  structureHint?: string;
}

const list: CompoundDef[] = [];
const idMap = new Map<string, CompoundDef>();

function reg(c: CompoundDef) {
  if (!idMap.has(c.id)) {
    idMap.set(c.id, c);
    list.push(c);
  }
}

// ----------------------------------------------------
// 1. OXIDES & SIMPLE CHALCOGENIDES (65 compounds)
// ----------------------------------------------------
reg({
  id: 'H2O',
  name: 'Water',
  formula: 'H₂O',
  category: 'oxide',
  state: 'liquid',
  appearance: 'Colorless, transparent liquid',
  description: 'The universal solvent and foundation of all known carbon-based life.',
  hazard: 'safe',
  bondType: 'polar covalent',
  color: '#06b6d4',
  glowColor: 'rgba(6, 182, 212, 0.4)',
  recipe: ['H', 'O'],
  condition: { heat: true },
  equation: '2H₂ + O₂ → 2H₂O',
  enthalpy: '-285.8 kJ/mol',
  funFact: 'Water expands by roughly 9% upon freezing, allowing ice to float atop oceans.',
  structureHint: 'Bent molecule, 104.5° angle',
});
reg({
  id: 'H2O2',
  name: 'Hydrogen Peroxide',
  formula: 'H₂O₂',
  category: 'oxide',
  state: 'liquid',
  appearance: 'Pale blue viscous liquid',
  description: 'A powerful oxidizing agent and bleach containing an unstable single oxygen-oxygen bond.',
  hazard: 'corrosive',
  bondType: 'covalent',
  color: '#38bdf8',
  glowColor: 'rgba(56, 189, 248, 0.4)',
  recipe: ['H2O', 'O'],
  condition: { electricity: true },
  equation: 'H₂O + [O] → H₂O₂',
  enthalpy: '-187.8 kJ/mol',
  funFact: 'Concentrated hydrogen peroxide is utilized as rocket monopropellant.',
});
reg({
  id: 'CO',
  name: 'Carbon Monoxide',
  formula: 'CO',
  category: 'oxide',
  state: 'gas',
  appearance: 'Colorless, odorless gas',
  description: 'A toxic gas formed by incomplete combustion; binds strongly to hemoglobin.',
  hazard: 'toxic',
  bondType: 'polar covalent',
  color: '#64748b',
  glowColor: 'rgba(100, 116, 139, 0.4)',
  recipe: ['C', 'O'],
  equation: '2C + O₂ → 2CO',
  enthalpy: '-110.5 kJ/mol',
  funFact: 'Binds to blood hemoglobin 200 times more tightly than oxygen does.',
});
reg({
  id: 'CO2',
  name: 'Carbon Dioxide',
  formula: 'CO₂',
  category: 'oxide',
  state: 'gas',
  appearance: 'Colorless, heavy gas subliming at -78.5 °C',
  description: 'Major greenhouse gas and carbon substrate for photosynthesis.',
  hazard: 'safe',
  bondType: 'covalent',
  color: '#94a3b8',
  glowColor: 'rgba(148, 163, 184, 0.4)',
  recipe: ['CO', 'O'],
  condition: { heat: true },
  equation: '2CO + O₂ → 2CO₂',
  enthalpy: '-393.5 kJ/mol',
  funFact: 'Dry ice sublimes directly from solid to gas without melting into liquid.',
});
reg({
  id: 'C3O2',
  name: 'Carbon Suboxide',
  formula: 'C₃O₂',
  category: 'oxide',
  state: 'gas',
  appearance: 'Pungent, suffocating lacrymatory gas',
  description: 'Unusual cumulene oxide O=C=C=C=O synthesized by dehydrating malonic acid.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#71717a',
  glowColor: 'rgba(113, 113, 122, 0.4)',
  recipe: ['C', 'CO2'],
  condition: { heat: true },
  equation: 'C + 2CO₂ → C₃O₂',
  enthalpy: '-93.7 kJ/mol',
  funFact: 'Spontaneously polymerizes into dark red-violet conductive macromolecular films.',
});
reg({
  id: 'SO2',
  name: 'Sulfur Dioxide',
  formula: 'SO₂',
  category: 'oxide',
  state: 'gas',
  appearance: 'Colorless choking gas with burning match odor',
  description: 'Formed by burning sulfur or roasting sulfide ores; wine antioxidant and preservative.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#eab308',
  glowColor: 'rgba(234, 179, 8, 0.4)',
  recipe: ['S', 'O'],
  condition: { heat: true },
  equation: 'S + O₂ → SO₂',
  enthalpy: '-296.8 kJ/mol',
  funFact: 'Used since Roman antiquity to sanitize oak wine barrels against souring bacteria.',
});
reg({
  id: 'SO3',
  name: 'Sulfur Trioxide',
  formula: 'SO₃',
  category: 'oxide',
  state: 'solid',
  appearance: 'Silky white fibrous needle crystals',
  description: 'Acid anhydride of sulfuric acid; reacts explosively with water to produce acid mist.',
  hazard: 'corrosive',
  bondType: 'covalent',
  color: '#f59e0b',
  glowColor: 'rgba(245, 158, 11, 0.4)',
  recipe: ['SO2', 'O'],
  condition: { catalyst: true },
  equation: '2SO₂ + O₂ → 2SO₃',
  enthalpy: '-395.7 kJ/mol',
  funFact: 'Contact process uses vanadium pentoxide (V₂O₅) catalyst to convert SO₂ to SO₃.',
});
reg({
  id: 'N2O',
  name: 'Nitrous Oxide (Laughing Gas)',
  formula: 'N₂O',
  category: 'oxide',
  state: 'gas',
  appearance: 'Sweet-smelling colorless gas',
  description: 'Inhaled dental anesthetic and vehicle nitrous oxide engine boost oxidizer.',
  hazard: 'safe',
  bondType: 'covalent',
  color: '#38bdf8',
  glowColor: 'rgba(56, 189, 248, 0.4)',
  recipe: ['N', 'O'],
  condition: { heat: true },
  equation: '2N₂ + O₂ → 2N₂O',
  enthalpy: '+82.0 kJ/mol',
  funFact: 'Also serves as the propellant in canned aerosol culinary whipped cream dispensers.',
});
reg({
  id: 'NO',
  name: 'Nitric Oxide',
  formula: 'NO',
  category: 'oxide',
  state: 'gas',
  appearance: 'Colorless paramagnetic free radical gas',
  description: 'Critical biological signaling molecule that dilates vascular smooth muscles.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#818cf8',
  glowColor: 'rgba(129, 140, 248, 0.4)',
  recipe: ['N2O', 'O'],
  condition: { heat: true },
  equation: '2N₂O + O₂ → 4NO',
  enthalpy: '+90.2 kJ/mol',
  funFact: 'The discovery of NO as a cardiovascular signaling messenger won the 1998 Nobel Prize.',
});
reg({
  id: 'NO2',
  name: 'Nitrogen Dioxide',
  formula: 'NO₂',
  category: 'oxide',
  state: 'gas',
  appearance: 'Acrid reddish-brown toxic smog gas',
  description: 'Key component of urban smog; exists in equilibrium with colorless dinitrogen tetroxide.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#b45309',
  glowColor: 'rgba(180, 83, 9, 0.4)',
  recipe: ['NO', 'O'],
  equation: '2NO + O₂ → 2NO₂',
  enthalpy: '+33.2 kJ/mol',
  funFact: 'Paramagnetic odd-electron radical responsible for the orange haze over polluted cities.',
});
reg({
  id: 'N2O3',
  name: 'Dinitrogen Trioxide',
  formula: 'N₂O₃',
  category: 'oxide',
  state: 'liquid',
  appearance: 'Deep sapphire-blue liquid at low temperatures',
  description: 'The anhydride of nitrous acid; dissociates readily into NO and NO₂ as it warms.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#2563eb',
  glowColor: 'rgba(37, 99, 235, 0.4)',
  recipe: ['NO', 'NO2'],
  equation: 'NO + NO₂ ⇌ N₂O₃',
  enthalpy: '+83.7 kJ/mol',
  funFact: 'Has an intense, jewel-like deep blue color in liquid form at -20 °C.',
});
reg({
  id: 'N2O4',
  name: 'Dinitrogen Tetroxide',
  formula: 'N₂O₄',
  category: 'oxide',
  state: 'liquid',
  appearance: 'Colorless to pale yellow liquid oxidizer',
  description: 'Hypergolic storable liquid rocket oxidizer paired with hydrazine on Apollo Lunar Modules.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#d97706',
  glowColor: 'rgba(217, 119, 6, 0.4)',
  recipe: ['NO2', 'NO2'],
  equation: '2NO₂ ⇌ N₂O₄',
  enthalpy: '+9.2 kJ/mol',
  funFact: 'Ignites spontaneously on contact with hydrazine fuels without needing a spark plug.',
});
reg({
  id: 'N2O5',
  name: 'Dinitrogen Pentoxide',
  formula: 'N₂O₅',
  category: 'oxide',
  state: 'solid',
  appearance: 'White, delicate subliming crystal solid',
  description: 'Anhydride of nitric acid; exists in solid state as nitronium nitrate [NO₂]⁺[NO₃]⁻.',
  hazard: 'corrosive',
  bondType: 'ionic',
  color: '#f8fafc',
  glowColor: 'rgba(248, 250, 252, 0.4)',
  recipe: ['NO2', 'O'],
  condition: { catalyst: true },
  equation: '4NO₂ + O₂ → 2N₂O₅',
  enthalpy: '+11.3 kJ/mol',
  funFact: 'A powerful nitrating agent that can convert organic materials directly into high explosives.',
});
reg({
  id: 'P4O6',
  name: 'Phosphorus Hexoxide (Trioxide)',
  formula: 'P₄O₆',
  category: 'oxide',
  state: 'solid',
  appearance: 'White, waxy, highly poisonous crystals',
  description: 'Formed by burning phosphorus in a limited supply of dry air; anhydride of phosphorous acid.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#fef08a',
  glowColor: 'rgba(254, 240, 138, 0.4)',
  recipe: ['P', 'O'],
  equation: 'P₄ + 3O₂ → P₄O₆',
  enthalpy: '-1640.1 kJ/mol',
  funFact: 'Exceedingly toxic; decomposes in hot water into phosphine gas and phosphoric acid.',
});
reg({
  id: 'P4O10',
  name: 'Phosphorus Pentoxide',
  formula: 'P₄O₁₀',
  category: 'oxide',
  state: 'solid',
  appearance: 'Snow-white deliquescent crystalline powder',
  description: 'One of the most potent chemical drying agents known; hisses violently as it absorbs water.',
  hazard: 'corrosive',
  bondType: 'covalent',
  color: '#f8fafc',
  glowColor: 'rgba(248, 250, 252, 0.5)',
  recipe: ['P4O6', 'O'],
  condition: { heat: true },
  equation: 'P₄O₆ + 2O₂ → P₄O₁₀',
  enthalpy: '-2984.0 kJ/mol',
  funFact: 'Can dehydrate concentrated pure sulfuric acid into sulfur trioxide gas.',
});
reg({
  id: 'SiO2',
  name: 'Silicon Dioxide (Quartz / Silica)',
  formula: 'SiO₂',
  category: 'oxide',
  state: 'solid',
  appearance: 'Transparent crystalline quartz rock and beach sand',
  description: 'Network covalent macromolecule; principal constituent of sand, quartz, and window glass.',
  hazard: 'safe',
  bondType: 'covalent',
  color: '#93c5fd',
  glowColor: 'rgba(147, 197, 253, 0.4)',
  recipe: ['Si', 'O'],
  condition: { heat: true },
  equation: 'Si + O₂ → SiO₂',
  enthalpy: '-910.7 kJ/mol',
  funFact: 'Piezoelectric quartz crystals vibrate at precisely 32,768 Hz in electronic wristwatches.',
});
reg({
  id: 'SiO',
  name: 'Silicon Monoxide',
  formula: 'SiO',
  category: 'oxide',
  state: 'solid',
  appearance: 'Brownish-black amorphous refractory solid',
  description: 'Vapor-deposited optical protective coating on precision telescope mirrors and laser lenses.',
  hazard: 'safe',
  bondType: 'covalent',
  color: '#78716c',
  glowColor: 'rgba(120, 113, 108, 0.4)',
  recipe: ['Si', 'SiO2'],
  condition: { heat: true },
  equation: 'Si + SiO₂ → 2SiO',
  enthalpy: '-100.4 kJ/mol',
  funFact: 'Identified in the interstellar dust clouds surrounding aging asymptotic giant branch stars.',
});
reg({
  id: 'Na2O',
  name: 'Sodium Oxide',
  formula: 'Na₂O',
  category: 'oxide',
  state: 'solid',
  appearance: 'White, strongly basic ceramic powder',
  description: 'Strongly alkaline base anhydride; hydrolyzes vigorously to yield sodium hydroxide.',
  hazard: 'corrosive',
  bondType: 'ionic',
  color: '#38bdf8',
  glowColor: 'rgba(56, 189, 248, 0.4)',
  recipe: ['Na', 'O'],
  condition: { heat: true },
  equation: '4Na + O₂ → 2Na₂O',
  enthalpy: '-414.2 kJ/mol',
  funFact: 'Forms roughly 15% of standard soda-lime window glass alongside silica and limestone.',
});
reg({
  id: 'Na2O2',
  name: 'Sodium Peroxide',
  formula: 'Na₂O₂',
  category: 'oxide',
  state: 'solid',
  appearance: 'Yellowish-white hygroscopic granular powder',
  description: 'Peroxide salt used in scuba rebreathers and submarines to scrub CO₂ while releasing pure O₂.',
  hazard: 'corrosive',
  bondType: 'ionic',
  color: '#facc15',
  glowColor: 'rgba(250, 204, 21, 0.4)',
  recipe: ['Na2O', 'O'],
  condition: { heat: true },
  equation: '2Na₂O + O₂ → 2Na₂O₂',
  enthalpy: '-510.9 kJ/mol',
  funFact: 'Releases life-supporting oxygen gas directly when exposed to human exhaled breath.',
});
reg({
  id: 'K2O',
  name: 'Potassium Oxide',
  formula: 'K₂O',
  category: 'oxide',
  state: 'solid',
  appearance: 'Pale yellow deliquescent solid',
  description: 'Alkali metal oxide; the standard benchmark by which commercial potassium fertilizers are graded (% K₂O).',
  hazard: 'corrosive',
  bondType: 'ionic',
  color: '#a855f7',
  glowColor: 'rgba(168, 85, 247, 0.4)',
  recipe: ['K', 'O'],
  condition: { heat: true },
  equation: '4K + O₂ → 2K₂O',
  enthalpy: '-361.5 kJ/mol',
  funFact: 'Reacts so violently with water that the resulting heat can ignite evolved hydrogen gas.',
});
reg({
  id: 'KO2',
  name: 'Potassium Superoxide',
  formula: 'KO₂',
  category: 'oxide',
  state: 'solid',
  appearance: 'Yellow paramagnetic salt containing superoxide O₂⁻',
  description: 'Paramagnetic yellow solid used in Russian Cosmonaut EVA space suits to generate metabolic oxygen.',
  hazard: 'corrosive',
  bondType: 'ionic',
  color: '#eab308',
  glowColor: 'rgba(234, 179, 8, 0.4)',
  recipe: ['K', 'O'],
  condition: { heat: true },
  equation: 'K + O₂ → KO₂',
  enthalpy: '-284.5 kJ/mol',
  funFact: '4KO₂ + 2CO₂ → 2K₂CO₃ + 3O₂: Captures metabolic carbon dioxide while producing breathable oxygen.',
});
reg({
  id: 'Li2O',
  name: 'Lithium Oxide (Lithia)',
  formula: 'Li₂O',
  category: 'oxide',
  state: 'solid',
  appearance: 'White, refractory crystalline ceramic',
  description: 'High-thermal-shock glass ceramic flux; added to CorningWare cookware to survive flame heating.',
  hazard: 'corrosive',
  bondType: 'ionic',
  color: '#ec4899',
  glowColor: 'rgba(236, 72, 153, 0.4)',
  recipe: ['Li', 'O'],
  condition: { heat: true },
  equation: '4Li + O₂ → 2Li₂O',
  enthalpy: '-597.8 kJ/mol',
  funFact: 'Gives oven-safe glassware zero thermal expansion, preventing shattering upon ice water shock.',
});
reg({
  id: 'CaO',
  name: 'Calcium Oxide (Quicklime)',
  formula: 'CaO',
  category: 'oxide',
  state: 'solid',
  appearance: 'Hard white alkaline mineral chunks',
  description: 'Quicklime; produced by calcining limestone in kilns; slakes exothermically with water.',
  hazard: 'corrosive',
  bondType: 'ionic',
  color: '#e2e8f0',
  glowColor: 'rgba(226, 232, 240, 0.4)',
  recipe: ['Ca', 'O'],
  condition: { heat: true },
  equation: '2Ca + O₂ → 2CaO',
  enthalpy: '-635.1 kJ/mol',
  funFact: 'Heated in oxyhydrogen flames in 19th-century theaters to create brilliant "limelight" stage illumination.',
});
reg({
  id: 'MgO',
  name: 'Magnesium Oxide (Magnesia)',
  formula: 'MgO',
  category: 'oxide',
  state: 'solid',
  appearance: 'White refractory mineral powder',
  description: 'Possesses an astonishing melting point of 2,852 °C; lines industrial steel blast furnace crucibles.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#f8fafc',
  glowColor: 'rgba(248, 250, 252, 0.4)',
  recipe: ['Mg', 'O'],
  condition: { heat: true },
  equation: '2Mg + O₂ → 2MgO',
  enthalpy: '-601.7 kJ/mol',
  funFact: 'Burns with such intense UV white brightness that looking directly at the flame can cause flash blindness.',
});
reg({
  id: 'Al2O3',
  name: 'Aluminium Oxide (Alumina / Corundum)',
  formula: 'Al₂O₃',
  category: 'oxide',
  state: 'solid',
  appearance: 'Ultra-hard crystalline corundum (sapphire / ruby)',
  description: 'Mohs hardness 9; forms natural sapphires and rubies (trace chromium); abrasive sandpaper grit.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#cbd5e1',
  glowColor: 'rgba(203, 213, 225, 0.4)',
  recipe: ['Al', 'O'],
  condition: { heat: true },
  equation: '4Al + 3O₂ → 2Al₂O₃',
  enthalpy: '-1675.7 kJ/mol',
  funFact: 'Forms an instantaneous nanometer-thin transparent passivation skin protecting aluminum metal from rust.',
});
reg({
  id: 'Fe2O3',
  name: 'Iron(III) Oxide (Rust / Hematite)',
  formula: 'Fe₂O₃',
  category: 'oxide',
  state: 'solid',
  appearance: 'Reddish-brown mineral pigment and rust',
  description: 'Hematite ore and common red rust; crushed into jeweler’s rouge polishing abrasive.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#ef4444',
  glowColor: 'rgba(239, 68, 68, 0.4)',
  recipe: ['Fe', 'O'],
  condition: { heat: true },
  equation: '4Fe + 3O₂ → 2Fe₂O₃',
  enthalpy: '-824.2 kJ/mol',
  funFact: 'Imparts the iconic rusty crimson color to the barren sands and skies of the planet Mars.',
});
reg({
  id: 'FeO',
  name: 'Iron(II) Oxide (Wüstite)',
  formula: 'FeO',
  category: 'oxide',
  state: 'solid',
  appearance: 'Black mineral powder',
  description: 'Non-stoichiometric black iron oxide (wüstite); forms during the initial smelting of iron ore in blast furnaces.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#27272a',
  glowColor: 'rgba(39, 39, 42, 0.4)',
  recipe: ['Fe', 'O'],
  condition: { heat: true },
  equation: '2Fe + O₂ → 2FeO',
  enthalpy: '-272.0 kJ/mol',
  funFact: 'Wüstite is naturally deficient in iron (Fe₁₋ₓO), creating crystal vacancies that permit rapid ion diffusion.',
});
reg({
  id: 'Fe3O4',
  name: 'Iron(II,III) Oxide (Magnetite / Lodestone)',
  formula: 'Fe₃O₄',
  category: 'oxide',
  state: 'solid',
  appearance: 'Black, naturally magnetic mineral stone',
  description: 'Lodestone; the most magnetic naturally occurring mineral on Earth; led to the invention of the magnetic compass.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#18181b',
  glowColor: 'rgba(24, 24, 27, 0.5)',
  recipe: ['FeO', 'Fe2O3'],
  condition: { heat: true },
  equation: 'FeO + Fe₂O₃ → Fe₃O₄',
  enthalpy: '-1118.4 kJ/mol',
  funFact: 'Ancient Greek navigators used naturally magnetized lodestone chunks suspended by threads to navigate oceans.',
});
reg({
  id: 'CuO',
  name: 'Copper(II) Oxide (Tenorite)',
  formula: 'CuO',
  category: 'oxide',
  state: 'solid',
  appearance: 'Jet-black crystalline powder',
  description: 'Black copper oxide; used in blue ceramic glazes and high-temperature cuprate superconductors.',
  hazard: 'toxic',
  bondType: 'ionic',
  color: '#0f172a',
  glowColor: 'rgba(15, 23, 42, 0.4)',
  recipe: ['Cu', 'O'],
  condition: { heat: true },
  equation: '2Cu + O₂ → 2CuO',
  enthalpy: '-157.3 kJ/mol',
  funFact: 'Used as an oxidizer in high-energy military thermite torch formulations alongside powdered aluminum.',
});
reg({
  id: 'Cu2O',
  name: 'Copper(I) Oxide (Cuprite)',
  formula: 'Cu₂O',
  category: 'oxide',
  state: 'solid',
  appearance: 'Reddish-brown octahedral mineral gemstone',
  description: 'Cuprite; ruby-red semiconductor used in marine antifouling paints to prevent barnacles on ship hulls.',
  hazard: 'toxic',
  bondType: 'ionic',
  color: '#991b1b',
  glowColor: 'rgba(153, 27, 27, 0.4)',
  recipe: ['Cu', 'CuO'],
  condition: { heat: true },
  equation: 'Cu + CuO → Cu₂O',
  enthalpy: '-168.6 kJ/mol',
  funFact: 'One of the earliest semiconductors researched in physics, demonstrating the photoelectric effect in the 1920s.',
});
reg({
  id: 'TiO2',
  name: 'Titanium Dioxide (Rutile)',
  formula: 'TiO₂',
  category: 'oxide',
  state: 'solid',
  appearance: 'Brilliant opaque white powder with ultra-high refractive index',
  description: 'The premier brilliant white pigment of modern paints, plastics, paper, and physical sunscreens.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#ffffff',
  glowColor: 'rgba(255, 255, 255, 0.6)',
  recipe: ['Ti', 'O'],
  condition: { heat: true },
  equation: 'Ti + O₂ → TiO₂',
  enthalpy: '-944.0 kJ/mol',
  funFact: 'Has a higher refractive index (n = 2.61) than natural diamond (n = 2.42), giving it unmatched opacity.',
});
reg({
  id: 'Ti2O3',
  name: 'Titanium(III) Oxide',
  formula: 'Ti₂O₃',
  category: 'oxide',
  state: 'solid',
  appearance: 'Dark violet-black lustrous semiconductor',
  description: 'Undergoes a famous insulator-to-metal electrical phase transition near 450 K.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#4c1d95',
  glowColor: 'rgba(76, 29, 149, 0.4)',
  recipe: ['TiO2', 'Ti'],
  condition: { heat: true },
  equation: '3TiO₂ + Ti → 2Ti₂O₃',
  enthalpy: '-1520.9 kJ/mol',
  funFact: 'Displays corundum crystal symmetry identical to natural red ruby and blue sapphire.',
});
reg({
  id: 'Ag2O',
  name: 'Silver(I) Oxide',
  formula: 'Ag₂O',
  category: 'oxide',
  state: 'solid',
  appearance: 'Fine dark brownish-black powder',
  description: 'Used in miniature silver-oxide button batteries powering wristwatches, calculators, and hearing aids.',
  hazard: 'safe',
  bondType: 'ionic',
  color: '#3f3f46',
  glowColor: 'rgba(63, 63, 70, 0.4)',
  recipe: ['Ag', 'O'],
  condition: { heat: true },
  equation: '4Ag + O₂ → 2Ag₂O',
  enthalpy: '-31.1 kJ/mol',
  funFact: 'Provides an exceptionally flat, stable 1.55-volt discharge curve until fully depleted in button cells.',
});
reg({
  id: 'Au2O3',
  name: 'Gold(III) Oxide',
  formula: 'Au₂O₃',
  category: 'oxide',
  state: 'solid',
  appearance: 'Brownish-orange thermally unstable powder',
  description: 'The only thermodynamically stable oxide of gold; decomposes into pure metallic gold at 160 °C.',
  hazard: 'safe',
  bondType: 'covalent',
  color: '#ca8a04',
  glowColor: 'rgba(202, 138, 4, 0.4)',
  recipe: ['Au', 'O'],
  condition: { heat: true, catalyst: true },
  equation: '4Au + 3O₂ → 2Au₂O₃',
  enthalpy: '-19.3 kJ/mol',
  funFact: 'Because gold is extremely noble, Au₂O₃ readily gives up its oxygen when gently heated.',
});
reg({
  id: 'PtO2',
  name: 'Platinum Dioxide (Adams’ Catalyst)',
  formula: 'PtO₂',
  category: 'oxide',
  state: 'solid',
  appearance: 'Dark brown, velvety catalytic powder',
  description: 'Adams’ catalyst; reduces smoothly in hydrogen gas into ultra-active catalytic platinum black.',
  hazard: 'safe',
  bondType: 'covalent',
  color: '#52525b',
  glowColor: 'rgba(82, 82, 91, 0.4)',
  recipe: ['Pt', 'O'],
  condition: { heat: true },
  equation: 'Pt + O₂ → PtO₂',
  enthalpy: '-167.4 kJ/mol',
  funFact: 'Hydrogenates delicate vegetable oils and pharmaceutical intermediates with exceptional efficiency.',
});
reg({
  id: 'UO2',
  name: 'Uranium Dioxide (Brown Oxide)',
  formula: 'UO₂',
  category: 'oxide',
  state: 'solid',
  appearance: 'Heavy, blackish-brown high-density ceramic pellets',
  description: 'The standard chemical fuel pellet loaded inside modern commercial nuclear power reactor fuel rods.',
  hazard: 'radioactive',
  bondType: 'ionic',
  color: '#15803d',
  glowColor: 'rgba(21, 128, 61, 0.6)',
  recipe: ['U', 'O'],
  condition: { heat: true },
  equation: 'U + O₂ → UO₂',
  enthalpy: '-1085.0 kJ/mol',
  funFact: 'Has an enormous melting point of 2,865 °C, allowing fuel rods to operate safely at extreme reactor core temperatures.',
});
reg({
  id: 'UO3',
  name: 'Uranium Trioxide (Orange Oxide)',
  formula: 'UO₃',
  category: 'oxide',
  state: 'solid',
  appearance: 'Vivid yellow-orange radioactive powder',
  description: 'Known as "orange oxide" in nuclear fuel reprocessing; intermediate between yellowcake and UF₆.',
  hazard: 'radioactive',
  bondType: 'ionic',
  color: '#ea580c',
  glowColor: 'rgba(234, 88, 12, 0.6)',
  recipe: ['UO2', 'O'],
  condition: { heat: true },
  equation: '2UO₂ + O₂ → 2UO₃',
  enthalpy: '-1223.8 kJ/mol',
  funFact: 'Historical artisan glassware makers added traces of UO₃ to produce brilliant yellow-green "Vaseline glass".',
});
reg({
  id: 'U3O8',
  name: 'Triuranium Octoxide ("Yellowcake" Calcined Form)',
  formula: 'U₃O₈',
  category: 'oxide',
  state: 'solid',
  appearance: 'Dark olive-green to black stable uranium ore concentrate',
  description: 'The most chemically stable oxide of uranium; forms when raw yellowcake ore is calcined in milling kilns.',
  hazard: 'radioactive',
  bondType: 'ionic',
  color: '#166534',
  glowColor: 'rgba(22, 101, 52, 0.6)',
  recipe: ['UO2', 'UO3'],
  condition: { heat: true },
  equation: 'UO₂ + 2UO₃ → U₃O₈',
  enthalpy: '-3574.8 kJ/mol',
  funFact: 'Can be stored in steel drums for centuries without degradation or dangerous pressure buildup.',
});
reg({
  id: 'Cl2O',
  name: 'Dichlorine Monoxide',
  formula: 'Cl₂O',
  category: 'oxide',
  state: 'gas',
  appearance: 'Brownish-yellow gas smelling of chlorine gas',
  description: 'Acid anhydride of hypochlorous acid (HClO); strong bleaching and chlorinating agent.',
  hazard: 'corrosive',
  bondType: 'covalent',
  color: '#84cc16',
  glowColor: 'rgba(132, 204, 22, 0.4)',
  recipe: ['Cl', 'O'],
  equation: '2Cl₂ + O₂ → 2Cl₂O',
  enthalpy: '+80.3 kJ/mol',
  funFact: 'Explodes violently if exposed to sparks or organic contaminants.',
});
reg({
  id: 'ClO2',
  name: 'Chlorine Dioxide',
  formula: 'ClO₂',
  category: 'oxide',
  state: 'gas',
  appearance: 'Yellowish-green paramagnetic gas',
  description: 'Paramagnetic gas used worldwide in municipal water plants and eco-friendly paper pulp bleaching without producing toxic dioxins.',
  hazard: 'toxic',
  bondType: 'covalent',
  color: '#a3e635',
  glowColor: 'rgba(163, 230, 53, 0.4)',
  recipe: ['Cl2O', 'O'],
  equation: 'Cl₂O + [O] → 2ClO₂',
  enthalpy: '+102.5 kJ/mol',
  funFact: 'Free of chlorinated hydrocarbon byproducts, making it the environmental gold standard for papermaking bleach.',
});
reg({
  id: 'Cl2O7',
  name: 'Dichlorine Heptoxide',
  formula: 'Cl₂O₇',
  category: 'oxide',
  state: 'liquid',
  appearance: 'Colorless, oily, shock-sensitive volatile liquid',
  description: 'Anhydride of perchloric acid; the highest oxidation state (+7) oxide of chlorine.',
  hazard: 'corrosive',
  bondType: 'covalent',
  color: '#4ade80',
  glowColor: 'rgba(74, 222, 128, 0.4)',
  recipe: ['ClO2', 'O'],
  condition: { catalyst: true },
  equation: '2ClO₂ + 3[O] → Cl₂O₇',
  enthalpy: '+272.0 kJ/mol',
  funFact: 'Detonates vigorously if struck or brought into contact with flame.',
});
reg({
  id: 'I2O5',
  name: 'Diiodine Pentoxide',
  formula: 'I₂O₅',
  category: 'oxide',
  state: 'solid',
  appearance: 'Dense white crystalline powder',
  description: 'Anhydride of iodic acid; quantitative reagent used in breathalyzers and gas sensors to measure trace carbon monoxide.',
  hazard: 'corrosive',
  bondType: 'covalent',
  color: '#c084fc',
  glowColor: 'rgba(192, 132, 252, 0.4)',
  recipe: ['I', 'O'],
  condition: { heat: true },
  equation: '2I₂ + 5O₂ → 2I₂O₅',
  enthalpy: '-158.1 kJ/mol',
  funFact: 'Reacts quantitatively with toxic CO gas to liberate elemental iodine: 5CO + I₂O₅ → I₂ + 5CO₂.',
});

console.log('Registered preliminary oxides. Total count:', list.length);
